// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	grpc "google.golang.org/grpc"
	emptypb "google.golang.org/protobuf/types/known/emptypb"

	mock "github.com/stretchr/testify/mock"

	update "github.com/1ncrease0/xkcd-search/proto/update"
)

// MockUpdateClient is an autogenerated mock type for the UpdateClient type
type MockUpdateClient struct {
	mock.Mock
}

type MockUpdateClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUpdateClient) EXPECT() *MockUpdateClient_Expecter {
	return &MockUpdateClient_Expecter{mock: &_m.Mock}
}

// Drop provides a mock function with given fields: ctx, in, opts
func (_m *MockUpdateClient) Drop(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Drop")
	}

	var r0 *emptypb.Empty
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *emptypb.Empty, ...grpc.CallOption) (*emptypb.Empty, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *emptypb.Empty, ...grpc.CallOption) *emptypb.Empty); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*emptypb.Empty)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *emptypb.Empty, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUpdateClient_Drop_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Drop'
type MockUpdateClient_Drop_Call struct {
	*mock.Call
}

// Drop is a helper method to define mock.On call
//   - ctx context.Context
//   - in *emptypb.Empty
//   - opts ...grpc.CallOption
func (_e *MockUpdateClient_Expecter) Drop(ctx interface{}, in interface{}, opts ...interface{}) *MockUpdateClient_Drop_Call {
	return &MockUpdateClient_Drop_Call{Call: _e.mock.On("Drop",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *MockUpdateClient_Drop_Call) Run(run func(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption)) *MockUpdateClient_Drop_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		run(args[0].(context.Context), args[1].(*emptypb.Empty), variadicArgs...)
	})
	return _c
}

func (_c *MockUpdateClient_Drop_Call) Return(_a0 *emptypb.Empty, _a1 error) *MockUpdateClient_Drop_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUpdateClient_Drop_Call) RunAndReturn(run func(context.Context, *emptypb.Empty, ...grpc.CallOption) (*emptypb.Empty, error)) *MockUpdateClient_Drop_Call {
	_c.Call.Return(run)
	return _c
}

// Ping provides a mock function with given fields: ctx, in, opts
func (_m *MockUpdateClient) Ping(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Ping")
	}

	var r0 *emptypb.Empty
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *emptypb.Empty, ...grpc.CallOption) (*emptypb.Empty, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *emptypb.Empty, ...grpc.CallOption) *emptypb.Empty); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*emptypb.Empty)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *emptypb.Empty, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUpdateClient_Ping_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Ping'
type MockUpdateClient_Ping_Call struct {
	*mock.Call
}

// Ping is a helper method to define mock.On call
//   - ctx context.Context
//   - in *emptypb.Empty
//   - opts ...grpc.CallOption
func (_e *MockUpdateClient_Expecter) Ping(ctx interface{}, in interface{}, opts ...interface{}) *MockUpdateClient_Ping_Call {
	return &MockUpdateClient_Ping_Call{Call: _e.mock.On("Ping",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *MockUpdateClient_Ping_Call) Run(run func(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption)) *MockUpdateClient_Ping_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		run(args[0].(context.Context), args[1].(*emptypb.Empty), variadicArgs...)
	})
	return _c
}

func (_c *MockUpdateClient_Ping_Call) Return(_a0 *emptypb.Empty, _a1 error) *MockUpdateClient_Ping_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUpdateClient_Ping_Call) RunAndReturn(run func(context.Context, *emptypb.Empty, ...grpc.CallOption) (*emptypb.Empty, error)) *MockUpdateClient_Ping_Call {
	_c.Call.Return(run)
	return _c
}

// Stats provides a mock function with given fields: ctx, in, opts
func (_m *MockUpdateClient) Stats(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*update.StatsReply, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Stats")
	}

	var r0 *update.StatsReply
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *emptypb.Empty, ...grpc.CallOption) (*update.StatsReply, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *emptypb.Empty, ...grpc.CallOption) *update.StatsReply); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*update.StatsReply)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *emptypb.Empty, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUpdateClient_Stats_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Stats'
type MockUpdateClient_Stats_Call struct {
	*mock.Call
}

// Stats is a helper method to define mock.On call
//   - ctx context.Context
//   - in *emptypb.Empty
//   - opts ...grpc.CallOption
func (_e *MockUpdateClient_Expecter) Stats(ctx interface{}, in interface{}, opts ...interface{}) *MockUpdateClient_Stats_Call {
	return &MockUpdateClient_Stats_Call{Call: _e.mock.On("Stats",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *MockUpdateClient_Stats_Call) Run(run func(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption)) *MockUpdateClient_Stats_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		run(args[0].(context.Context), args[1].(*emptypb.Empty), variadicArgs...)
	})
	return _c
}

func (_c *MockUpdateClient_Stats_Call) Return(_a0 *update.StatsReply, _a1 error) *MockUpdateClient_Stats_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUpdateClient_Stats_Call) RunAndReturn(run func(context.Context, *emptypb.Empty, ...grpc.CallOption) (*update.StatsReply, error)) *MockUpdateClient_Stats_Call {
	_c.Call.Return(run)
	return _c
}

// Status provides a mock function with given fields: ctx, in, opts
func (_m *MockUpdateClient) Status(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*update.StatusReply, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Status")
	}

	var r0 *update.StatusReply
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *emptypb.Empty, ...grpc.CallOption) (*update.StatusReply, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *emptypb.Empty, ...grpc.CallOption) *update.StatusReply); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*update.StatusReply)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *emptypb.Empty, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUpdateClient_Status_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Status'
type MockUpdateClient_Status_Call struct {
	*mock.Call
}

// Status is a helper method to define mock.On call
//   - ctx context.Context
//   - in *emptypb.Empty
//   - opts ...grpc.CallOption
func (_e *MockUpdateClient_Expecter) Status(ctx interface{}, in interface{}, opts ...interface{}) *MockUpdateClient_Status_Call {
	return &MockUpdateClient_Status_Call{Call: _e.mock.On("Status",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *MockUpdateClient_Status_Call) Run(run func(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption)) *MockUpdateClient_Status_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		run(args[0].(context.Context), args[1].(*emptypb.Empty), variadicArgs...)
	})
	return _c
}

func (_c *MockUpdateClient_Status_Call) Return(_a0 *update.StatusReply, _a1 error) *MockUpdateClient_Status_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUpdateClient_Status_Call) RunAndReturn(run func(context.Context, *emptypb.Empty, ...grpc.CallOption) (*update.StatusReply, error)) *MockUpdateClient_Status_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, in, opts
func (_m *MockUpdateClient) Update(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *emptypb.Empty
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *emptypb.Empty, ...grpc.CallOption) (*emptypb.Empty, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *emptypb.Empty, ...grpc.CallOption) *emptypb.Empty); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*emptypb.Empty)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *emptypb.Empty, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUpdateClient_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockUpdateClient_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - in *emptypb.Empty
//   - opts ...grpc.CallOption
func (_e *MockUpdateClient_Expecter) Update(ctx interface{}, in interface{}, opts ...interface{}) *MockUpdateClient_Update_Call {
	return &MockUpdateClient_Update_Call{Call: _e.mock.On("Update",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *MockUpdateClient_Update_Call) Run(run func(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption)) *MockUpdateClient_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		run(args[0].(context.Context), args[1].(*emptypb.Empty), variadicArgs...)
	})
	return _c
}

func (_c *MockUpdateClient_Update_Call) Return(_a0 *emptypb.Empty, _a1 error) *MockUpdateClient_Update_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUpdateClient_Update_Call) RunAndReturn(run func(context.Context, *emptypb.Empty, ...grpc.CallOption) (*emptypb.Empty, error)) *MockUpdateClient_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUpdateClient creates a new instance of MockUpdateClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUpdateClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUpdateClient {
	mock := &MockUpdateClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
