// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	core "github.com/1ncrease0/xkcd-search/search/core"
	mock "github.com/stretchr/testify/mock"
)

// MockDB is an autogenerated mock type for the DB type
type MockDB struct {
	mock.Mock
}

type MockDB_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDB) EXPECT() *MockDB_Expecter {
	return &MockDB_Expecter{mock: &_m.Mock}
}

// Get provides a mock function with given fields: ctx, ID
func (_m *MockDB) Get(ctx context.Context, ID int) (core.Comics, error) {
	ret := _m.Called(ctx, ID)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 core.Comics
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) (core.Comics, error)); ok {
		return rf(ctx, ID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) core.Comics); ok {
		r0 = rf(ctx, ID)
	} else {
		r0 = ret.Get(0).(core.Comics)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, ID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockDB_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockDB_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - ID int
func (_e *MockDB_Expecter) Get(ctx interface{}, ID interface{}) *MockDB_Get_Call {
	return &MockDB_Get_Call{Call: _e.mock.On("Get", ctx, ID)}
}

func (_c *MockDB_Get_Call) Run(run func(ctx context.Context, ID int)) *MockDB_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int))
	})
	return _c
}

func (_c *MockDB_Get_Call) Return(_a0 core.Comics, _a1 error) *MockDB_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockDB_Get_Call) RunAndReturn(run func(context.Context, int) (core.Comics, error)) *MockDB_Get_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx
func (_m *MockDB) List(ctx context.Context) ([]core.ComicsWithWords, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []core.ComicsWithWords
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]core.ComicsWithWords, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []core.ComicsWithWords); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]core.ComicsWithWords)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockDB_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockDB_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockDB_Expecter) List(ctx interface{}) *MockDB_List_Call {
	return &MockDB_List_Call{Call: _e.mock.On("List", ctx)}
}

func (_c *MockDB_List_Call) Run(run func(ctx context.Context)) *MockDB_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockDB_List_Call) Return(_a0 []core.ComicsWithWords, _a1 error) *MockDB_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockDB_List_Call) RunAndReturn(run func(context.Context) ([]core.ComicsWithWords, error)) *MockDB_List_Call {
	_c.Call.Return(run)
	return _c
}

// Search provides a mock function with given fields: ctx, keyword
func (_m *MockDB) Search(ctx context.Context, keyword string) ([]int, error) {
	ret := _m.Called(ctx, keyword)

	if len(ret) == 0 {
		panic("no return value specified for Search")
	}

	var r0 []int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]int, error)); ok {
		return rf(ctx, keyword)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []int); ok {
		r0 = rf(ctx, keyword)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]int)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, keyword)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockDB_Search_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Search'
type MockDB_Search_Call struct {
	*mock.Call
}

// Search is a helper method to define mock.On call
//   - ctx context.Context
//   - keyword string
func (_e *MockDB_Expecter) Search(ctx interface{}, keyword interface{}) *MockDB_Search_Call {
	return &MockDB_Search_Call{Call: _e.mock.On("Search", ctx, keyword)}
}

func (_c *MockDB_Search_Call) Run(run func(ctx context.Context, keyword string)) *MockDB_Search_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockDB_Search_Call) Return(_a0 []int, _a1 error) *MockDB_Search_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockDB_Search_Call) RunAndReturn(run func(context.Context, string) ([]int, error)) *MockDB_Search_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockDB creates a new instance of MockDB. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDB(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDB {
	mock := &MockDB{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
