// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	grpc "google.golang.org/grpc"
	emptypb "google.golang.org/protobuf/types/known/emptypb"

	mock "github.com/stretchr/testify/mock"

	words "github.com/1ncrease0/xkcd-search/proto/words"
)

// MockWordsClient is an autogenerated mock type for the WordsClient type
type MockWordsClient struct {
	mock.Mock
}

type MockWordsClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockWordsClient) EXPECT() *MockWordsClient_Expecter {
	return &MockWordsClient_Expecter{mock: &_m.Mock}
}

// Norm provides a mock function with given fields: ctx, in, opts
func (_m *MockWordsClient) Norm(ctx context.Context, in *words.WordsRequest, opts ...grpc.CallOption) (*words.WordsReply, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Norm")
	}

	var r0 *words.WordsReply
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *words.WordsRequest, ...grpc.CallOption) (*words.WordsReply, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *words.WordsRequest, ...grpc.CallOption) *words.WordsReply); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*words.WordsReply)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *words.WordsRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockWordsClient_Norm_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Norm'
type MockWordsClient_Norm_Call struct {
	*mock.Call
}

// Norm is a helper method to define mock.On call
//   - ctx context.Context
//   - in *words.WordsRequest
//   - opts ...grpc.CallOption
func (_e *MockWordsClient_Expecter) Norm(ctx interface{}, in interface{}, opts ...interface{}) *MockWordsClient_Norm_Call {
	return &MockWordsClient_Norm_Call{Call: _e.mock.On("Norm",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *MockWordsClient_Norm_Call) Run(run func(ctx context.Context, in *words.WordsRequest, opts ...grpc.CallOption)) *MockWordsClient_Norm_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		run(args[0].(context.Context), args[1].(*words.WordsRequest), variadicArgs...)
	})
	return _c
}

func (_c *MockWordsClient_Norm_Call) Return(_a0 *words.WordsReply, _a1 error) *MockWordsClient_Norm_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockWordsClient_Norm_Call) RunAndReturn(run func(context.Context, *words.WordsRequest, ...grpc.CallOption) (*words.WordsReply, error)) *MockWordsClient_Norm_Call {
	_c.Call.Return(run)
	return _c
}

// Ping provides a mock function with given fields: ctx, in, opts
func (_m *MockWordsClient) Ping(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Ping")
	}

	var r0 *emptypb.Empty
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *emptypb.Empty, ...grpc.CallOption) (*emptypb.Empty, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *emptypb.Empty, ...grpc.CallOption) *emptypb.Empty); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*emptypb.Empty)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *emptypb.Empty, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockWordsClient_Ping_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Ping'
type MockWordsClient_Ping_Call struct {
	*mock.Call
}

// Ping is a helper method to define mock.On call
//   - ctx context.Context
//   - in *emptypb.Empty
//   - opts ...grpc.CallOption
func (_e *MockWordsClient_Expecter) Ping(ctx interface{}, in interface{}, opts ...interface{}) *MockWordsClient_Ping_Call {
	return &MockWordsClient_Ping_Call{Call: _e.mock.On("Ping",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *MockWordsClient_Ping_Call) Run(run func(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption)) *MockWordsClient_Ping_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		run(args[0].(context.Context), args[1].(*emptypb.Empty), variadicArgs...)
	})
	return _c
}

func (_c *MockWordsClient_Ping_Call) Return(_a0 *emptypb.Empty, _a1 error) *MockWordsClient_Ping_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockWordsClient_Ping_Call) RunAndReturn(run func(context.Context, *emptypb.Empty, ...grpc.CallOption) (*emptypb.Empty, error)) *MockWordsClient_Ping_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockWordsClient creates a new instance of MockWordsClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockWordsClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockWordsClient {
	mock := &MockWordsClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
