// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	core "github.com/1ncrease0/xkcd-search/update/core"
	mock "github.com/stretchr/testify/mock"
)

// MockDB is an autogenerated mock type for the DB type
type MockDB struct {
	mock.Mock
}

type MockDB_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDB) EXPECT() *MockDB_Expecter {
	return &MockDB_Expecter{mock: &_m.Mock}
}

// Add provides a mock function with given fields: _a0, _a1
func (_m *MockDB) Add(_a0 context.Context, _a1 core.Comics) error {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Add")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, core.Comics) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockDB_Add_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Add'
type MockDB_Add_Call struct {
	*mock.Call
}

// Add is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 core.Comics
func (_e *MockDB_Expecter) Add(_a0 interface{}, _a1 interface{}) *MockDB_Add_Call {
	return &MockDB_Add_Call{Call: _e.mock.On("Add", _a0, _a1)}
}

func (_c *MockDB_Add_Call) Run(run func(_a0 context.Context, _a1 core.Comics)) *MockDB_Add_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(core.Comics))
	})
	return _c
}

func (_c *MockDB_Add_Call) Return(_a0 error) *MockDB_Add_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockDB_Add_Call) RunAndReturn(run func(context.Context, core.Comics) error) *MockDB_Add_Call {
	_c.Call.Return(run)
	return _c
}

// Drop provides a mock function with given fields: _a0
func (_m *MockDB) Drop(_a0 context.Context) error {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for Drop")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockDB_Drop_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Drop'
type MockDB_Drop_Call struct {
	*mock.Call
}

// Drop is a helper method to define mock.On call
//   - _a0 context.Context
func (_e *MockDB_Expecter) Drop(_a0 interface{}) *MockDB_Drop_Call {
	return &MockDB_Drop_Call{Call: _e.mock.On("Drop", _a0)}
}

func (_c *MockDB_Drop_Call) Run(run func(_a0 context.Context)) *MockDB_Drop_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockDB_Drop_Call) Return(_a0 error) *MockDB_Drop_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockDB_Drop_Call) RunAndReturn(run func(context.Context) error) *MockDB_Drop_Call {
	_c.Call.Return(run)
	return _c
}

// IDs provides a mock function with given fields: _a0
func (_m *MockDB) IDs(_a0 context.Context) ([]int, error) {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for IDs")
	}

	var r0 []int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]int, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []int); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]int)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockDB_IDs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IDs'
type MockDB_IDs_Call struct {
	*mock.Call
}

// IDs is a helper method to define mock.On call
//   - _a0 context.Context
func (_e *MockDB_Expecter) IDs(_a0 interface{}) *MockDB_IDs_Call {
	return &MockDB_IDs_Call{Call: _e.mock.On("IDs", _a0)}
}

func (_c *MockDB_IDs_Call) Run(run func(_a0 context.Context)) *MockDB_IDs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockDB_IDs_Call) Return(_a0 []int, _a1 error) *MockDB_IDs_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockDB_IDs_Call) RunAndReturn(run func(context.Context) ([]int, error)) *MockDB_IDs_Call {
	_c.Call.Return(run)
	return _c
}

// Stats provides a mock function with given fields: _a0
func (_m *MockDB) Stats(_a0 context.Context) (core.DBStats, error) {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for Stats")
	}

	var r0 core.DBStats
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (core.DBStats, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(context.Context) core.DBStats); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(core.DBStats)
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockDB_Stats_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Stats'
type MockDB_Stats_Call struct {
	*mock.Call
}

// Stats is a helper method to define mock.On call
//   - _a0 context.Context
func (_e *MockDB_Expecter) Stats(_a0 interface{}) *MockDB_Stats_Call {
	return &MockDB_Stats_Call{Call: _e.mock.On("Stats", _a0)}
}

func (_c *MockDB_Stats_Call) Run(run func(_a0 context.Context)) *MockDB_Stats_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockDB_Stats_Call) Return(_a0 core.DBStats, _a1 error) *MockDB_Stats_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockDB_Stats_Call) RunAndReturn(run func(context.Context) (core.DBStats, error)) *MockDB_Stats_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockDB creates a new instance of MockDB. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDB(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDB {
	mock := &MockDB{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
