// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockUpdateNotifier is an autogenerated mock type for the UpdateNotifier type
type MockUpdateNotifier struct {
	mock.Mock
}

type MockUpdateNotifier_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUpdateNotifier) EXPECT() *MockUpdateNotifier_Expecter {
	return &MockUpdateNotifier_Expecter{mock: &_m.Mock}
}

// Notify provides a mock function with given fields: ctx
func (_m *MockUpdateNotifier) Notify(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Notify")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockUpdateNotifier_Notify_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Notify'
type MockUpdateNotifier_Notify_Call struct {
	*mock.Call
}

// Notify is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockUpdateNotifier_Expecter) Notify(ctx interface{}) *MockUpdateNotifier_Notify_Call {
	return &MockUpdateNotifier_Notify_Call{Call: _e.mock.On("Notify", ctx)}
}

func (_c *MockUpdateNotifier_Notify_Call) Run(run func(ctx context.Context)) *MockUpdateNotifier_Notify_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockUpdateNotifier_Notify_Call) Return(_a0 error) *MockUpdateNotifier_Notify_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockUpdateNotifier_Notify_Call) RunAndReturn(run func(context.Context) error) *MockUpdateNotifier_Notify_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUpdateNotifier creates a new instance of MockUpdateNotifier. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUpdateNotifier(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUpdateNotifier {
	mock := &MockUpdateNotifier{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
