// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockWords is an autogenerated mock type for the Words type
type MockWords struct {
	mock.Mock
}

type MockWords_Expecter struct {
	mock *mock.Mock
}

func (_m *MockWords) EXPECT() *MockWords_Expecter {
	return &MockWords_Expecter{mock: &_m.Mock}
}

// Norm provides a mock function with given fields: ctx, phrase
func (_m *MockWords) Norm(ctx context.Context, phrase string) ([]string, error) {
	ret := _m.Called(ctx, phrase)

	if len(ret) == 0 {
		panic("no return value specified for Norm")
	}

	var r0 []string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]string, error)); ok {
		return rf(ctx, phrase)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []string); ok {
		r0 = rf(ctx, phrase)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, phrase)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockWords_Norm_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Norm'
type MockWords_Norm_Call struct {
	*mock.Call
}

// Norm is a helper method to define mock.On call
//   - ctx context.Context
//   - phrase string
func (_e *MockWords_Expecter) Norm(ctx interface{}, phrase interface{}) *MockWords_Norm_Call {
	return &MockWords_Norm_Call{Call: _e.mock.On("Norm", ctx, phrase)}
}

func (_c *MockWords_Norm_Call) Run(run func(ctx context.Context, phrase string)) *MockWords_Norm_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockWords_Norm_Call) Return(_a0 []string, _a1 error) *MockWords_Norm_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockWords_Norm_Call) RunAndReturn(run func(context.Context, string) ([]string, error)) *MockWords_Norm_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockWords creates a new instance of MockWords. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockWords(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockWords {
	mock := &MockWords{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
