// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	core "github.com/1ncrease0/xkcd-search/update/core"
	mock "github.com/stretchr/testify/mock"
)

// MockXKCD is an autogenerated mock type for the XKCD type
type MockXKCD struct {
	mock.Mock
}

type MockXKCD_Expecter struct {
	mock *mock.Mock
}

func (_m *MockXKCD) EXPECT() *MockXKCD_Expecter {
	return &MockXKCD_Expecter{mock: &_m.Mock}
}

// Get provides a mock function with given fields: _a0, _a1
func (_m *MockXKCD) Get(_a0 context.Context, _a1 int) (core.XKCDInfo, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 core.XKCDInfo
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) (core.XKCDInfo, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) core.XKCDInfo); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Get(0).(core.XKCDInfo)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockXKCD_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockXKCD_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 int
func (_e *MockXKCD_Expecter) Get(_a0 interface{}, _a1 interface{}) *MockXKCD_Get_Call {
	return &MockXKCD_Get_Call{Call: _e.mock.On("Get", _a0, _a1)}
}

func (_c *MockXKCD_Get_Call) Run(run func(_a0 context.Context, _a1 int)) *MockXKCD_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int))
	})
	return _c
}

func (_c *MockXKCD_Get_Call) Return(_a0 core.XKCDInfo, _a1 error) *MockXKCD_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockXKCD_Get_Call) RunAndReturn(run func(context.Context, int) (core.XKCDInfo, error)) *MockXKCD_Get_Call {
	_c.Call.Return(run)
	return _c
}

// LastID provides a mock function with given fields: _a0
func (_m *MockXKCD) LastID(_a0 context.Context) (int, error) {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for LastID")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (int, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(context.Context) int); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockXKCD_LastID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LastID'
type MockXKCD_LastID_Call struct {
	*mock.Call
}

// LastID is a helper method to define mock.On call
//   - _a0 context.Context
func (_e *MockXKCD_Expecter) LastID(_a0 interface{}) *MockXKCD_LastID_Call {
	return &MockXKCD_LastID_Call{Call: _e.mock.On("LastID", _a0)}
}

func (_c *MockXKCD_LastID_Call) Run(run func(_a0 context.Context)) *MockXKCD_LastID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockXKCD_LastID_Call) Return(_a0 int, _a1 error) *MockXKCD_LastID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockXKCD_LastID_Call) RunAndReturn(run func(context.Context) (int, error)) *MockXKCD_LastID_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockXKCD creates a new instance of MockXKCD. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockXKCD(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockXKCD {
	mock := &MockXKCD{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
