// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	grpc "google.golang.org/grpc"
	emptypb "google.golang.org/protobuf/types/known/emptypb"

	mock "github.com/stretchr/testify/mock"

	search "github.com/1ncrease0/xkcd-search/proto/search"
)

// MockSearchClient is an autogenerated mock type for the SearchClient type
type MockSearchClient struct {
	mock.Mock
}

type MockSearchClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSearchClient) EXPECT() *MockSearchClient_Expecter {
	return &MockSearchClient_Expecter{mock: &_m.Mock}
}

// ISearch provides a mock function with given fields: ctx, in, opts
func (_m *MockSearchClient) ISearch(ctx context.Context, in *search.SearchRequest, opts ...grpc.CallOption) (*search.SearchReply, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for ISearch")
	}

	var r0 *search.SearchReply
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *search.SearchRequest, ...grpc.CallOption) (*search.SearchReply, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *search.SearchRequest, ...grpc.CallOption) *search.SearchReply); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*search.SearchReply)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *search.SearchRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSearchClient_ISearch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ISearch'
type MockSearchClient_ISearch_Call struct {
	*mock.Call
}

// ISearch is a helper method to define mock.On call
//   - ctx context.Context
//   - in *search.SearchRequest
//   - opts ...grpc.CallOption
func (_e *MockSearchClient_Expecter) ISearch(ctx interface{}, in interface{}, opts ...interface{}) *MockSearchClient_ISearch_Call {
	return &MockSearchClient_ISearch_Call{Call: _e.mock.On("ISearch",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *MockSearchClient_ISearch_Call) Run(run func(ctx context.Context, in *search.SearchRequest, opts ...grpc.CallOption)) *MockSearchClient_ISearch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		run(args[0].(context.Context), args[1].(*search.SearchRequest), variadicArgs...)
	})
	return _c
}

func (_c *MockSearchClient_ISearch_Call) Return(_a0 *search.SearchReply, _a1 error) *MockSearchClient_ISearch_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSearchClient_ISearch_Call) RunAndReturn(run func(context.Context, *search.SearchRequest, ...grpc.CallOption) (*search.SearchReply, error)) *MockSearchClient_ISearch_Call {
	_c.Call.Return(run)
	return _c
}

// Ping provides a mock function with given fields: ctx, in, opts
func (_m *MockSearchClient) Ping(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Ping")
	}

	var r0 *emptypb.Empty
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *emptypb.Empty, ...grpc.CallOption) (*emptypb.Empty, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *emptypb.Empty, ...grpc.CallOption) *emptypb.Empty); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*emptypb.Empty)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *emptypb.Empty, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSearchClient_Ping_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Ping'
type MockSearchClient_Ping_Call struct {
	*mock.Call
}

// Ping is a helper method to define mock.On call
//   - ctx context.Context
//   - in *emptypb.Empty
//   - opts ...grpc.CallOption
func (_e *MockSearchClient_Expecter) Ping(ctx interface{}, in interface{}, opts ...interface{}) *MockSearchClient_Ping_Call {
	return &MockSearchClient_Ping_Call{Call: _e.mock.On("Ping",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *MockSearchClient_Ping_Call) Run(run func(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption)) *MockSearchClient_Ping_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		run(args[0].(context.Context), args[1].(*emptypb.Empty), variadicArgs...)
	})
	return _c
}

func (_c *MockSearchClient_Ping_Call) Return(_a0 *emptypb.Empty, _a1 error) *MockSearchClient_Ping_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSearchClient_Ping_Call) RunAndReturn(run func(context.Context, *emptypb.Empty, ...grpc.CallOption) (*emptypb.Empty, error)) *MockSearchClient_Ping_Call {
	_c.Call.Return(run)
	return _c
}

// Search provides a mock function with given fields: ctx, in, opts
func (_m *MockSearchClient) Search(ctx context.Context, in *search.SearchRequest, opts ...grpc.CallOption) (*search.SearchReply, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Search")
	}

	var r0 *search.SearchReply
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *search.SearchRequest, ...grpc.CallOption) (*search.SearchReply, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *search.SearchRequest, ...grpc.CallOption) *search.SearchReply); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*search.SearchReply)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *search.SearchRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSearchClient_Search_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Search'
type MockSearchClient_Search_Call struct {
	*mock.Call
}

// Search is a helper method to define mock.On call
//   - ctx context.Context
//   - in *search.SearchRequest
//   - opts ...grpc.CallOption
func (_e *MockSearchClient_Expecter) Search(ctx interface{}, in interface{}, opts ...interface{}) *MockSearchClient_Search_Call {
	return &MockSearchClient_Search_Call{Call: _e.mock.On("Search",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *MockSearchClient_Search_Call) Run(run func(ctx context.Context, in *search.SearchRequest, opts ...grpc.CallOption)) *MockSearchClient_Search_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		run(args[0].(context.Context), args[1].(*search.SearchRequest), variadicArgs...)
	})
	return _c
}

func (_c *MockSearchClient_Search_Call) Return(_a0 *search.SearchReply, _a1 error) *MockSearchClient_Search_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSearchClient_Search_Call) RunAndReturn(run func(context.Context, *search.SearchRequest, ...grpc.CallOption) (*search.SearchReply, error)) *MockSearchClient_Search_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockSearchClient creates a new instance of MockSearchClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSearchClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSearchClient {
	mock := &MockSearchClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
