// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	core "github.com/1ncrease0/xkcd-search/search/core"
	mock "github.com/stretchr/testify/mock"
)

// MockSearcher is an autogenerated mock type for the Searcher type
type MockSearcher struct {
	mock.Mock
}

type MockSearcher_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSearcher) EXPECT() *MockSearcher_Expecter {
	return &MockSearcher_Expecter{mock: &_m.Mock}
}

// BuildIndex provides a mock function with given fields: ctx
func (_m *MockSearcher) BuildIndex(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for BuildIndex")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockSearcher_BuildIndex_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BuildIndex'
type MockSearcher_BuildIndex_Call struct {
	*mock.Call
}

// BuildIndex is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockSearcher_Expecter) BuildIndex(ctx interface{}) *MockSearcher_BuildIndex_Call {
	return &MockSearcher_BuildIndex_Call{Call: _e.mock.On("BuildIndex", ctx)}
}

func (_c *MockSearcher_BuildIndex_Call) Run(run func(ctx context.Context)) *MockSearcher_BuildIndex_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockSearcher_BuildIndex_Call) Return(_a0 error) *MockSearcher_BuildIndex_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSearcher_BuildIndex_Call) RunAndReturn(run func(context.Context) error) *MockSearcher_BuildIndex_Call {
	_c.Call.Return(run)
	return _c
}

// ISearch provides a mock function with given fields: ctx, phrase, limit
func (_m *MockSearcher) ISearch(ctx context.Context, phrase string, limit int) ([]core.Comics, error) {
	ret := _m.Called(ctx, phrase, limit)

	if len(ret) == 0 {
		panic("no return value specified for ISearch")
	}

	var r0 []core.Comics
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int) ([]core.Comics, error)); ok {
		return rf(ctx, phrase, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, int) []core.Comics); ok {
		r0 = rf(ctx, phrase, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]core.Comics)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, int) error); ok {
		r1 = rf(ctx, phrase, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSearcher_ISearch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ISearch'
type MockSearcher_ISearch_Call struct {
	*mock.Call
}

// ISearch is a helper method to define mock.On call
//   - ctx context.Context
//   - phrase string
//   - limit int
func (_e *MockSearcher_Expecter) ISearch(ctx interface{}, phrase interface{}, limit interface{}) *MockSearcher_ISearch_Call {
	return &MockSearcher_ISearch_Call{Call: _e.mock.On("ISearch", ctx, phrase, limit)}
}

func (_c *MockSearcher_ISearch_Call) Run(run func(ctx context.Context, phrase string, limit int)) *MockSearcher_ISearch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(int))
	})
	return _c
}

func (_c *MockSearcher_ISearch_Call) Return(_a0 []core.Comics, _a1 error) *MockSearcher_ISearch_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSearcher_ISearch_Call) RunAndReturn(run func(context.Context, string, int) ([]core.Comics, error)) *MockSearcher_ISearch_Call {
	_c.Call.Return(run)
	return _c
}

// Search provides a mock function with given fields: ctx, phrase, limit
func (_m *MockSearcher) Search(ctx context.Context, phrase string, limit int) ([]core.Comics, error) {
	ret := _m.Called(ctx, phrase, limit)

	if len(ret) == 0 {
		panic("no return value specified for Search")
	}

	var r0 []core.Comics
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int) ([]core.Comics, error)); ok {
		return rf(ctx, phrase, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, int) []core.Comics); ok {
		r0 = rf(ctx, phrase, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]core.Comics)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, int) error); ok {
		r1 = rf(ctx, phrase, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSearcher_Search_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Search'
type MockSearcher_Search_Call struct {
	*mock.Call
}

// Search is a helper method to define mock.On call
//   - ctx context.Context
//   - phrase string
//   - limit int
func (_e *MockSearcher_Expecter) Search(ctx interface{}, phrase interface{}, limit interface{}) *MockSearcher_Search_Call {
	return &MockSearcher_Search_Call{Call: _e.mock.On("Search", ctx, phrase, limit)}
}

func (_c *MockSearcher_Search_Call) Run(run func(ctx context.Context, phrase string, limit int)) *MockSearcher_Search_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(int))
	})
	return _c
}

func (_c *MockSearcher_Search_Call) Return(_a0 []core.Comics, _a1 error) *MockSearcher_Search_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSearcher_Search_Call) RunAndReturn(run func(context.Context, string, int) ([]core.Comics, error)) *MockSearcher_Search_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockSearcher creates a new instance of MockSearcher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSearcher(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSearcher {
	mock := &MockSearcher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
