// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	core "github.com/1ncrease0/xkcd-search/update/core"
	mock "github.com/stretchr/testify/mock"
)

// MockUpdater is an autogenerated mock type for the Updater type
type MockUpdater struct {
	mock.Mock
}

type MockUpdater_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUpdater) EXPECT() *MockUpdater_Expecter {
	return &MockUpdater_Expecter{mock: &_m.Mock}
}

// Drop provides a mock function with given fields: _a0
func (_m *MockUpdater) Drop(_a0 context.Context) error {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for Drop")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockUpdater_Drop_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Drop'
type MockUpdater_Drop_Call struct {
	*mock.Call
}

// Drop is a helper method to define mock.On call
//   - _a0 context.Context
func (_e *MockUpdater_Expecter) Drop(_a0 interface{}) *MockUpdater_Drop_Call {
	return &MockUpdater_Drop_Call{Call: _e.mock.On("Drop", _a0)}
}

func (_c *MockUpdater_Drop_Call) Run(run func(_a0 context.Context)) *MockUpdater_Drop_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockUpdater_Drop_Call) Return(_a0 error) *MockUpdater_Drop_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockUpdater_Drop_Call) RunAndReturn(run func(context.Context) error) *MockUpdater_Drop_Call {
	_c.Call.Return(run)
	return _c
}

// Stats provides a mock function with given fields: _a0
func (_m *MockUpdater) Stats(_a0 context.Context) (core.ServiceStats, error) {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for Stats")
	}

	var r0 core.ServiceStats
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (core.ServiceStats, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(context.Context) core.ServiceStats); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(core.ServiceStats)
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUpdater_Stats_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Stats'
type MockUpdater_Stats_Call struct {
	*mock.Call
}

// Stats is a helper method to define mock.On call
//   - _a0 context.Context
func (_e *MockUpdater_Expecter) Stats(_a0 interface{}) *MockUpdater_Stats_Call {
	return &MockUpdater_Stats_Call{Call: _e.mock.On("Stats", _a0)}
}

func (_c *MockUpdater_Stats_Call) Run(run func(_a0 context.Context)) *MockUpdater_Stats_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockUpdater_Stats_Call) Return(_a0 core.ServiceStats, _a1 error) *MockUpdater_Stats_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUpdater_Stats_Call) RunAndReturn(run func(context.Context) (core.ServiceStats, error)) *MockUpdater_Stats_Call {
	_c.Call.Return(run)
	return _c
}

// Status provides a mock function with given fields: _a0
func (_m *MockUpdater) Status(_a0 context.Context) core.ServiceStatus {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for Status")
	}

	var r0 core.ServiceStatus
	if rf, ok := ret.Get(0).(func(context.Context) core.ServiceStatus); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(core.ServiceStatus)
	}

	return r0
}

// MockUpdater_Status_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Status'
type MockUpdater_Status_Call struct {
	*mock.Call
}

// Status is a helper method to define mock.On call
//   - _a0 context.Context
func (_e *MockUpdater_Expecter) Status(_a0 interface{}) *MockUpdater_Status_Call {
	return &MockUpdater_Status_Call{Call: _e.mock.On("Status", _a0)}
}

func (_c *MockUpdater_Status_Call) Run(run func(_a0 context.Context)) *MockUpdater_Status_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockUpdater_Status_Call) Return(_a0 core.ServiceStatus) *MockUpdater_Status_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockUpdater_Status_Call) RunAndReturn(run func(context.Context) core.ServiceStatus) *MockUpdater_Status_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: _a0
func (_m *MockUpdater) Update(_a0 context.Context) error {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockUpdater_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockUpdater_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - _a0 context.Context
func (_e *MockUpdater_Expecter) Update(_a0 interface{}) *MockUpdater_Update_Call {
	return &MockUpdater_Update_Call{Call: _e.mock.On("Update", _a0)}
}

func (_c *MockUpdater_Update_Call) Run(run func(_a0 context.Context)) *MockUpdater_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockUpdater_Update_Call) Return(_a0 error) *MockUpdater_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockUpdater_Update_Call) RunAndReturn(run func(context.Context) error) *MockUpdater_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUpdater creates a new instance of MockUpdater. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUpdater(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUpdater {
	mock := &MockUpdater{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
